// Generated by CoffeeScript 1.8.0
(function() {
  var move;

  move = function(e) {
    return $(this).parent().children('.pane').toggleClass('clicked');
  };

  $(document).ready(function() {
    $('.pane').click(move);
  });

}).call(this);
