// Generated by CoffeeScript 1.8.0
(function() {
  window.explanations = {
    dropbox: {
      title: Dropbox,
      explanation: 'I\'m ecstatic to announce that I\'ll be interning at Dropbox in San Franciso this summer! I haven\'t been given a team quite yet, but I\'ll likely be working on the frontend or backend on one of their web services. Dropbox\'s culture stands out against all the companies I\'ve spoken with for potential internships, and I can\'t wait to start working there!'
    }
  };

}).call(this);
